execute_process(
  COMMAND ${TEST_COMPILER} -std=gnu++26 -freflection -fmodules-ts
          -fmodule-mapper=${TEST_MAPPER} -fsyntax-only ${TEST_SOURCE}
  RESULT_VARIABLE compile_result
  OUTPUT_VARIABLE compile_output
  ERROR_VARIABLE compile_error)

if(compile_result EQUAL 0)
  message(FATAL_ERROR "Invalid record compiled successfully: ${TEST_SOURCE}")
endif()

if(TEST_EXPECTED STREQUAL "unsupported_annotation")
  set(expected_text "unsupported field annotation")
elseif(TEST_EXPECTED STREQUAL "contradictory_annotations")
  set(expected_text "contradictory field modification annotations")
elseif(TEST_EXPECTED STREQUAL "invalid_member_type")
  set(expected_text "record data members must have tbl::field<T> type")
elseif(TEST_EXPECTED STREQUAL "incompatible_inheritance")
  set(expected_text "incompatible inherited field types")
elseif(TEST_EXPECTED STREQUAL "expression_cycle")
  set(expected_text "field expression cycle")
elseif(TEST_EXPECTED STREQUAL "unresolved_reference")
  set(expected_text "unresolved field reference")
elseif(TEST_EXPECTED STREQUAL "expression_type_mismatch")
  set(expected_text "field reference has the wrong value type")
elseif(TEST_EXPECTED STREQUAL "record_expression_cycle")
  set(expected_text "field expression cycle")
elseif(TEST_EXPECTED STREQUAL "unselected_expression_cycle")
  set(expected_text "field expression cycle")
elseif(TEST_EXPECTED STREQUAL "invalid_record_reference")
  set(expected_text "record reference target must be a definition")
elseif(TEST_EXPECTED STREQUAL "unresolved_record_field")
  set(expected_text "unresolved field reference")
elseif(TEST_EXPECTED STREQUAL "record_reference_type_mismatch")
  set(expected_text "record reference has the wrong value type")
elseif(TEST_EXPECTED STREQUAL "negative_shift")
  set(expected_text "negative bit shift count")
elseif(TEST_EXPECTED STREQUAL "invalid_list_index")
  set(expected_text "list index out of range")
elseif(TEST_EXPECTED STREQUAL "invalid_bit_slice")
  set(expected_text "bit slice out of range")
elseif(TEST_EXPECTED STREQUAL "unmarked_override")
  set(expected_text "inherited field requires explicit override")
elseif(TEST_EXPECTED STREQUAL "orphan_override")
  set(expected_text "local override has no inherited field")
elseif(TEST_EXPECTED STREQUAL "override_type_mismatch")
  set(expected_text "local override must have identical field type")
elseif(TEST_EXPECTED STREQUAL "override_final" OR TEST_EXPECTED STREQUAL
                                          "transitive_override_final" OR
       TEST_EXPECTED STREQUAL "conflicting_final_override")
  set(expected_text "cannot override final field")
elseif(TEST_EXPECTED STREQUAL "branch_override_conflict")
  set(expected_text "unresolved inherited field conflict")
else()
  message(FATAL_ERROR "Unknown negative test: ${TEST_EXPECTED}")
endif()

if(NOT compile_error MATCHES "${expected_text}")
  message(
    FATAL_ERROR "Expected ${TEST_EXPECTED} diagnostic, got:\n${compile_error}")
endif()
