name: CoreGear CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      # Uses the official action to check out the code
      uses: actions/checkout@v6

    - name: Install Nix
      uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6

    - name: Validate flake and run lint
      run: |
        nix flake check --no-build
        nix run .#lint
  gcc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      # Uses the official action to check out the code
      uses: actions/checkout@v6

    - name: Install Nix
      uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6

    - name: Run everything
      # Configures, builds and tests the project
      run: nix run .#check
  clang:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      # Uses the official action to check out the code
      uses: actions/checkout@v6

    - name: Install Nix
      uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6

    - name: Run everything
      # Configures, builds and tests the project
      run: nix run .#check-clang
